export const strings = {
    header: "Austin White",
    jobTitle: "Software Engineer",
    subHeader: ["Android", "React Native", "React"],
    aboutMeTitle: "About Me",
    aboutMeText: "I specialize in architecting mobile applications where connectivity and data integrity are reliability-critical. From integrated smart home ecosystems to autonomous robot swarms, I have a proven track record of delivering resilient, performant architectures in high-pressure environments. I’m driven by the challenge of making complex technology feel seamless and reliable for the end-user, no matter how high the stakes are.",
    skillsHeader: "Skills",
    skills: [
        "TypeScript",
        "Kotlin",
        "JavaScript",
        "Java",
        "React Native",
        "Android",
        "React",
        "HTML",
        "CSS",
        "Git",
        "GitHub Copilot",
        "GitHub Actions",
        "Android App Widgets",
        "Android WorkManager",
        "XML",
        "Firebase",
        "Yarn",
        "Jest",
        "Retrofit",
        "Axios",
        "Jotai",
        "React Hooks",
        "Cursor",

    ],
    experienceHeader: "Experience",
    companies: ["SmartRent"],
    jrEngineerTitle: "Junior Software Engineer",
    jrEngineerPoints: [
        "Drove a significant improvement in average app rating (from 2.1 to 4.2) by strategically deploying in-app review prompts, resulting in increased user satisfaction and positive app store feedback",
        "Prepared the SmartRent Resident App for international expansion by implementing an international environment specifically to accommodate GDPR requirements, enabling the app to launch in European markets.",
        "Implemented user interfaces from wireframes, ensuring alignment with design guidelines",
        "Implemented deep links for resident account registration, enhancing app onboarding and leveraging deep links to improve user retention",
        "Contributed to the rewrite of the SmartRent Resident app in React Native using TypeScript, enabling the integration of in-house design system components for a unified user experience across all company products",
    ],
    engOneTitle: "Software Engineer I",
    engOnePoints: [
        "Led projects to implement Community-focused features for the SmartRent Resident App, including Package Management, Amenity Reservations, and Community Broadcasts",
        "Led the planning and implementation of infrastructure for language localization in the app, while adding support for both English and Spanish languages to improve user experience",
        "Developed and implemented Firebase analytics for the app, providing detailed insights into user behavior and app usage patterns",
        "Ranked in the top 10% of performers in the Engineering department in the 2024 year-end review, earning the designation of 'key-performer' for consistently delivering high-quality code and demonstrating a strong receptiveness to feedback."
    ],
    engTwoTitle: "Software Engineer II",
    engTwoPoints: [
        "Designed and documented (via RFC) a system for authenticating Native Android Widgets with the React Native app, establishing a framework for secure user session and access control management",
        "Led the development of interactive IoT device control Android Widgets for Smart Locks and Thermostats, enabling users to quickly and directly adjust settings and monitor device status from their home screen",
        "Engineered an in-house Native Android solution for secure storage of sensitive user data, replacing a problematic third-party package that caused unintended user logouts",
    ],
    educationHeader: "Education",
    university: "California State University, Stanislaus",
    classOf: "Class of 2020",
    degree: "Bachelor of Arts in English",
    extracurriculars: "Extracurriculars",
    activities: ["Computer Science Club (President)", "StanHacks (Founder, Director)"],
    linkedIn: "LinkedIn",
    github: "GitHub",
    projectsHeader: "Projects",
    projectsSubHeader: "Click Image to view in color",
    deviceWidgets: "Android IoT Device Widgets",
    deviceWidgetsDescription: "For my Android Widgets project, I developed native Android Widgets for the SmartRent Resident app. This was particularly interesting because the main app itself is built in React Native, so I got to bridge that gap. I created widgets that let users control their smart locks directly from their home screen for quick locking/unlocking, and also widgets for operating smart thermostats to adjust temperatures instantly. My focus was on making sure these widgets were super functional, highly performant (so they updated smoothly and responded fast), and really easy to use for residents.",
    packages: "Packages",
    packagesDescription: "For my Packages project, I was responsible for developing a new feature that allowed residents to track their incoming packages within the SmartRent Resident app. This involved building out the functionality that enabled residents to monitor the status of their deliveries from arrival to being ready for pickup from the community's package room, aiming to create a seamless and clear experience for package retrieval.",
    localization: "App Localization",
    localizationDescription: "For my Localization project, I was responsible for implementing and optimizing the system to support both English and Spanish, along with corresponding date formats, across the application. This ensured a more tailored and accessible experience based on user preferences. (Note: Project wasn't fully finished)",
    broadcasts: "Community Broadcasts",
    broadcastsDescription: "For my Community Broadcasts project, I developed a feature that allowed property managers to send direct messages to residents through the app. This enabled them to quickly and efficiently update residents on important information, ensuring clear communication about community-wide announcements or issues.",
}
