export const strings = {
    header: "Austin White",
    subHeader: "Software Engineer | React Native, Android",
    aboutMeTitle: "About Me",
    aboutMeText: "I am a Software Engineer with a strong track record of building high-quality mobile applications that enhance user experience and deliver measurable impact. I've led and contributed to critical projects from concept to deployment, consistently driving improvements in performance, usability, and reliability. I thrive on solving complex technical challenges and am passionate about using technology to create innovative, user-centered solutions.",
    skillsHeader: "Skills",
    skills: [
        "TypeScript",
        "Kotlin",
        "JavaScript",
        "Java",
        "Git",
        "React Native",
        "Android SDK",
        "Android App Widgets",
        "Android WorkManager",
        "XML",
        "Firebase",
        "Yarn",
        "Jest",
        "Retrofit",
        "Axios",
        "Jotai"
    ],
    experienceHeader: "Experience",
    companies: ["SmartRent"],
    jrEngineerTitle: "Junior Software Engineer",
    jrEngineerPoints: [
        "Drove a significant improvement in average app rating (from 2.1 to 4.2) by strategically deploying in-app review prompts, resulting in increased user satisfaction and positive app store feedback",
        "Prepared the SmartRent Resident App for international expansion by implementing an international environment specifically to accommodate GDPR requirements, enabling the app to launch in European markets.",
        "Implemented user interfaces from wireframes, ensuring alignment with design guidelines",
        "Implemented deep links for resident account registration, enhancing app onboarding and leveraging deep links to improve user retention",
        "Contributed to the rewrite of the SmartRent Resident app in React Native using TypeScript, enabling the integration of in-house design system components for a unified user experience across all company products",
    ],
    engOneTitle: "Software Engineer I",
    engOnePoints: [
        "Led projects to implement Community-focused features for the SmartRent Resident App, including Package Management, Amenity Reservations, and Community Broadcasts",
        "Led the planning and implementation of infrastructure for language localization in the app, while adding support for both English and Spanish languages to improve user experience",
        "Developed and implemented Firebase analytics for the app, providing detailed insights into user behavior and app usage patterns",
        "Ranked in the top 10% of performers in the Engineering department in the 2024 year-end review, earning the designation of 'key-performer' for consistently delivering high-quality code and demonstrating a strong receptiveness to feedback."
    ],
    engTwoTitle: "Software Engineer II",
    engTwoPoints: [
        "Designed and documented (via RFC) a system for authenticating Native Android Widgets with the React Native app, establishing a framework for secure user session and access control management",
        "Led the development of interactive IoT device control Android Widgets for Smart Locks and Thermostats, enabling users to quickly and directly adjust settings and monitor device status from their home screen",
        "Engineered an in-house Native Android solution for secure storage of sensitive user data, replacing a problematic third-party package that caused unintended user logouts",
    ],
    educationHeader: "Education",
    university: "California State University, Stanislaus",
    classOf: "Class of 2020",
    degree: "Bachelor of Arts in English",
    extracurriculars: "Extracurriculars:",
    activities: ["Computer Science Club (President)", "StanHacks (Founder, Director)"]
}
